<script lang="ts">
    import {
        Home,
        BookOpen,
        Calendar,
        Heart,
        Search,
        Plus,
        Edit,
        Trash2,
        User,
        Users,
        FileText,
        Upload,
        Download,
        Folder,
        Settings,
        ChevronRight,
        ChevronLeft,
        ChevronDown,
        ChevronUp,
        X,
        XCircle,
        Check,
        CheckCircle,
        AlertCircle,
        Info,
        Menu,
        LogOut,
        Moon,
        Sun,
        Globe,
        Star,
        Clock,
        Mail,
        Lock,
        Eye,
        EyeOff,
        ArrowLeft,
        ArrowRight,
        MoreVertical,
        Filter,
        SortAsc,
        SortDesc,
        RefreshCw,
        Bell,
        Bookmark,
        Share2,
        MessageSquare,
        ThumbsUp,
        TrendingUp,
        BarChart3,
        PieChart,
        Zap,
        Award,
        Target,
        Layers,
        HelpCircle,
        File,
        MessageCircle,
        List,
        Loader,
        Play,
        Paperclip,
        Copy,
        Book
    } from 'lucide-svelte';

    const iconMap = {
        home: Home,
        subjects: BookOpen,
        semesters: Calendar,
        favorites: Heart,
        search: Search,
        add: Plus,
        plus: Plus,
        edit: Edit,
        delete: Trash2,
        trash: Trash2,
        user: User,
        users: Users,
        document: FileText,
        'file-text': FileText,
        upload: Upload,
        download: Download,
        folder: Folder,
        settings: Settings,
        'chevron-right': ChevronRight,
        'chevron-left': ChevronLeft,
        'chevron-down': ChevronDown,
        'chevron-up': ChevronUp,
        close: X,
        x: X,
        'x-circle': XCircle,
        check: Check,
        'check-circle': CheckCircle,
        alert: AlertCircle,
        'alert-circle': AlertCircle,
        info: Info,
        menu: Menu,
        logout: LogOut,
        moon: Moon,
        sun: Sun,
        globe: Globe,
        star: Star,
        clock: Clock,
        mail: Mail,
        lock: Lock,
        eye: Eye,
        'eye-off': EyeOff,
        'arrow-left': ArrowLeft,
        'arrow-right': ArrowRight,
        'more-vertical': MoreVertical,
        filter: Filter,
        'sort-asc': SortAsc,
        'sort-desc': SortDesc,
        refresh: RefreshCw,
        bell: Bell,
        bookmark: Bookmark,
        share: Share2,
        message: MessageSquare,
        like: ThumbsUp,
        trending: TrendingUp,
        'bar-chart': BarChart3,
        'pie-chart': PieChart,
        zap: Zap,
        award: Award,
        target: Target,
        layers: Layers,
        'help-circle': HelpCircle,
        file: File,
        'message-circle': MessageCircle,
        questions: HelpCircle,
        list: List,
        loader: Loader,
        play: Play,
        paperclip: Paperclip,
        copy: Copy,
        book: Book,
        chat: MessageCircle
    };

    export let name: keyof typeof iconMap | string;
    export let size = 24;
    export let className = '';
    export let strokeWidth = 2;

    $: IconComponent = iconMap[name] || AlertCircle;
</script>

<IconComponent
    {size}
    strokeWidth={strokeWidth}
    class="inline-block transition-all duration-200 {className}"
/>

